koreatech-algorithm-study/algorithm

baekjoon/14888/14888_김은서.py

풀이: 재귀 + 완전탐색
재귀로 연산자 삽입 순서에 따른 모든 경우를 다 구했습니다.
그리고 값이 리턴될때마다 max, min을 갱신해서 최종 최대/최소값을 구했습니다.

[Day2] 연산자 끼워넣기(14888)_김은서

---

baekjoon/14888/14888_김상현.py

1. 더하기(add), 빼기(sub), 곱하기(mul), 나누기(div)의 개수만큼 해당 문자열을 가지는 배열 operator를 생성한다.
2. 해당 배열을 순열을 통해 만들 수 있는 모든 조합의 순서 식(expression)을 구한다.
3. "식의 계산은 연산자 우선 순위를 무시하고 앞에서부터 진행해야 한다." 는 문제 조건에 부합하게 연산식을 계산한다.
3-1. 연산 방법은 calcuator() 함수 방식에 따른다.
4. 연산 결과를 비교하여 최대값과 최소값을 구한다.

[Day2] 연산자 끼워넣기(14888)_김상현

---

BOJ/2146/2146_황인호.py

코드 개요
- 섬 별로 BFS를 사용해 방문하다가 바다를 발견하면 해안가의 좌표를 섬 별로 저장(island)
- 섬 간 해안가의 좌표들의 거리 값을 모두 내어 1 이상의 값을 출력
구현 방법 고민 및 문제점
- 처음 문제를 보고 위의 방식으로 할지, 아니면 최초의 섬에서 바다로 나오면 바다를 방문하며 다음 섬까지의 최소 거리를 방문과 동시에 계산하는 방식으로 할지 고민이 있었다
- 나의 방법에서는 섬의 내부 좌표는 계산하지 않는다 쳐도 조합의 수가 많아, 계산 시간이 오래 걸릴 수 있겠다는 생각이 들었다.
- 하지만 구현하기 쉽지 않아, 현재의 방법으로 진행했다.

[Day1] 다리 만들기(2146)_황인호

---

BOJ/14888/14888_황인호.py
BOJ/2146/2146_황인호.py

코드 개요
- 연산자 인덱스를 개수만큼 나열하여 그 중 조합 리스트를 저장한다.
- 조합 인덱스 중 순서는 중요하되, 같은 연산 간의 순서는 중요하지 않으니 리스트를 집합으로 바꾼다.
- 연산자 조합 리스트를 부르트포스로 계산하여 최대값, 최소값 출력.

[Day2] 연산자 끼워넣기(14888)_황인호

---

baekjoon/14888/14888.py

연산자의 모든 경우의 수를 permutations 모듈을 통해 구한 뒤
set 객체에 넣어 중복 경우의 수를 제거했습니다.
만들어진 연산자를 숫자와 조합한 식을 eval 함수를 통해 바로 연산하려했으나,
나눗셈연산의 조건이 일반적인 식과 다른 것을 보고 계산기 클래스를 만들어 // 연산만 다르게 하도록 만든 뒤,
해당 클래스와 숫자, 연산자들을 조합해 계산을 수행했습니다.
* eval 함수는 함수 내에 입력된 문자열에 대해 바로 결과값을 반환하는 파이썬 내장함수입니다.

[Day2] 연산자 끼워넣기(14888)_김우헌

---

baekjoon/15486/15486_김상현.py

1. 동적 프로그래밍(DP)을 활용한 백트래킹 방식으로 문제 풀이에 접근하였다.
2. 퇴사일(N)부터 첫날(1)까지의 순서로 백준이가 벌 수 있는 최대의 금액을 누적으로 계산한다.
https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-15486-%ED%87%B4%EC%82%AC-2-Python

[Day3] 퇴사 2(15486)_김상현

---

baekjoon/15486/15486_김우헌.py

본 풀이는 DP 점화식을 떠올리지 못해 은서, 상현님의 풀이를 참고했음을 밝힙니다.
처음에는 i+day째 날의 이익이 0이겠지만, DP를 진행하다보면 이전에 상담을 진행해 i+day째 날의 이익이 
이전에 상담을 진행하여 값이 있는 경우가 있다는 것을 코드를 살피며 알았습니다.
해당 일에 상담을 하는경우와 하지 않는 경우의 최대값을 비교해 i+day째 날의 이익을 구합니다.

[Day3] 퇴사2(15486)_김우헌

---

baekjoon/2467/2467_김우헌.py

각 용액에 대해 다른 용액과 합쳐 특성값이 0과 가장 가까워지는 경우를 이진탐색을 통해 구했습니다.
모든 용액에 대해 용액리스트 안에서 이진탐색을 진행합니다. (대상 용액을 A, 탐색 용액을 B 라고 가칭하겠습니다)
- A == B 라면 무시하고 건너갑니다.
- 그렇지 않다면 A, B를 섞은 특성값을 구해 이전 최솟값과 비교해 더 작다면 대체합니다. 
- A 용액에 대해 이진탐색을 완료했다면 결과로 나온 nearby (작은용액, 큰용액, abs(특성값)) 변수를 리스트에 삽입합니다.
- 모든 용액에 대해 탐색이 끝났다면 리스트를 정렬해 특성값이 0에 가장 가까운 경우의 작은용액, 큰용액 값을 출력합니다.

[Day4] 용액(2467)_김우헌

---

baekjoon/15681/15681_김우헌.py

힌트에 풀이기법에 대한 샘플코드가 있어 쉽게 풀 수 있었습니다.
하지만 풀이에 사용된 개념은 상당히 어려워 보입니다.
1. 정점 및 간선 정보를 dict 객체를 통해 저장해둔뒤 R을 루트로한 트리를 생성합니다.
2. 재귀호출을 통해 자신을 포함한 자신을 루트로한 서브트리의 개수를 세는 countSubtreeNodes 를 정의합니다.
3. 루트 R을 인자로 countSubtreeNodes 함수를 실행하면 재귀호출로 루트 및 모든 노드에 대하여
자신을 포함한 자신을 루트로한 서브트리의 개수를 구할 수 있습니다.

[Day6] 트리와 쿼리(15681)_김우헌

---

baekjoon/2467/2467_김상현.py

1. 두 용액을 선택하는 기준이 되는 인덱스 값을 저장할 start 와 end 에 각각 0 과 N-1 값을 할당한다.
2. start 와 end 에 해당하는 용액을 혼합한 특성값(avg)을 구한다.
3. 두 용액을 혼합한 특성값의 절대값이 0에 가장 가까운 경우 정답값을 갱신한다.
4. 두 용액을 혼합한 특성값에 따라 용액을 교체해 준다.
4-1. 만약 두 용액을 혼합한 특성값이 0보다 작다면 start 의 값을 증가시켜 첫 번째 용액의 값을 증가시킨다.
4-2. 반대로 두 용액을 혼합한 특성값이 0보다 크다면 end 의 값을 감소시켜 두 번째 용액의 값을 감소시킨다.

[Day4] 용액(2467)_김상현

---

baekjoon/2447/2447_김상현.py

별(*) 로 구성된 N x N 크기의 배열을 생성한 후 9등분하여 가운데 배열은 공백(' ') 으로 값을 바꾸고, 나머지 배열은 재귀 함수를 통해 다시 처음부터 진행한다.

[Day5] 별 찍기 - 10(2447)_김상현

---

baekjoon/14426/14426_김상현.py

- N 개의 문자열 중에서 word 와 가장 유사한 문자를 bisect() 함수를 통해 찾는다.
- bisect() 함수를 이용하기 위해서는 N 개의 문자열을 저장한 배열 S 는 오름차순으로 정렬되어 있어야 한다.
- 파이썬에서 문자열에 사용할 수 있는 startswith() 를 사용하여 접두사를 확인할 수 있다.

[Day9] 접두사 찾기(14426)_김상현

---

baekjoon/2467/2467_김은서.py

투 포인터로 양쪽에서 left, right를 좁혀나가는 방식으로 풀었습니다 :~)

[Day4] 용액(2467)_김은서

---

baekjoon/2447/2447_김은서.py

① 사각형의 영역 나누기
재귀를 통해서 사각형을 쪼갤 수 있을 때까지 쪼갭니다.
이때,
- prev_gap으로 쪼개기 전 사각형의 영역을 알 수 있고,
- curr_gap으로는 다음에 쪼갤 사각형의 크기를 알 수 있습니다.
② 사각형의 빈칸 칠하기
재귀 탐색을 역으로 다시 올라오면서
현재 사각형 영역의 중앙부분을 ' '(빈칸)으로 채워넣습니다.
그림으로 한번 그려봤습니당. 재귀는 그림으로 그리면 이해가 빨리 되는 것 같아요.

 [Day5] 별 찍기 - 10(2447)_김은서

---

baekjoon/2623/2623_김은서.py

위상정렬을 사용하여 풀었습니다 :)
BFS를 진행하면서 노드를 방문할때마다 연결된 이웃 노드들의 진입차수(in_degree)를 1씩 감소시키고
연결된 이웃 노드들 중 진입차수가 0이 되는 노드들을 다음에 방문 가능하도록 구현했습니다.

[Day7] 음악프로그램(2623)_김은서

---

baekjoon/15681/15681_김상현.py

하단의 힌트 에서 주어진 makeTree() 함수와 countSubtreeNodes() 함수를 코드에 적용하여 문제를 해결하였다.
`setrecursionlimit(10**6)` 최대 재귀 깊이의 값을 10^6 으로 재설정하여 RecursionError 를 방지할 수 있었다.

[Day6] 트리와 쿼리(15681)_김상현

---

baekjoon/2623/2623_김상현.py

1. 각 노드의 진입 차수의 정보를 담은 리스트(indegree)를 생성한다.
2. 각 노드에 연결된 간선 정보를 담기 위한 연결 리스트(graph)를 생성한다.
3. 방향 그래프의 모든 간선 정보를 입력 받는다.
4. indegree 와 graph 정보를 활용하여 위상 정렬(topology_sort)을 진행한다.
4-1. 위상 정렬 결과를 담을 리스트(result) 와 위상 정렬을 위해 필요한 자료구조인 큐(queue)를 생성한다.
4-2. 시작점으로 진입차수가 0인 노드를 큐(queue)에 삽입한다.
4-3. 큐(queue)에 먼저 들어간 원소(first in)를 꺼내서 위상 정렬 결과를 담을 리스트(result)에 추가한다.
4-4. 해당 원소와 연결된 노드들의 진입차수에서 1을 뺀다.
4-5. 진입차수 1을 뺀 원소의 진입차수가 0이라면 현재 원소를 큐(queue)에 삽입한다.

[Day7] 음악프로그램(2623)_김상현

---

baekjoon/17835/17835_김상현.py

모든 노드를 시작점으로 단 한번 다익스트라를 적용하여 면접장 기준 최장 거리에 존재하는 도시의 번호와 거리를 구할 수 있었다.

[Day8] 면접보는 승범이네(17835)_김상현

---

baekjoon/1941/1941_김상현.py

DFS를 활용한 백트래킹 방식을 이용하여 문제를 해결하였다.
https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-1941-%EC%86%8C%EB%AC%B8%EB%82%9C-%EC%B9%A0%EA%B3%B5%EC%A3%BC-Python

[Day14] 소문난 칠공주(1941)_김상현

---

baekjoon/2660/2660_김상현.py

양방향 그래프의 한 노드에서 다른 모든 노드에 도달하기 위해 필요한 최소한의 연결선의 개수를 구하는 문제이다.
일반적인 BFS 를 변형하여 문제를 해결하였다.

[Day15] 회장뽑기(2660)_김상현

---

baekjoon/1647/1647_김상현.py

1. 입력받은 길의 정보(`edges`)를 길의 유지비(`x[2]`) 기준으로 정렬
2. 주어진 길의 정보(`edges`)를 이용항 Kruskal 알고리즘 적용
- 만약 현재 연결한 길의 수가 `N - 2`개(2개의 마을로 분할된 상태)라면 `Kruskal` 알고리즘을 종료한다.
- 만약 현재 주어진 길을 연결할 경우 마을에 사이클이 생기는 경우 `if find(A) != find(B):`
즉, 굳이 연결되어도 되지 않아도 되는 길은 연결하지 않는다.
- 위의 경우를 제외한 길은 `find()` 함수를 통해 연결하고 현재 길의 유지비를 `answer` 에 추가한다.

[Day17] 도시 분할 계획(1647)_김상현

---

baekjoon/1956/1956_김상현.py

📌 [자세한 내용은 요기로](https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-1956-%EC%9A%B4%EB%8F%99-Python)
- **힙(`heap`) 자료구조**를 이용하여 문제를 해결하였다.
- 그래프의 간선(`edge`)에 가중치(`weight`)가 존재하고, 최단 거리를 구하는 문제를 해결할 때 힙을 사용하면 된다는 경험이 생각나서 적용하여 문제를 풀었더니 바로 해결할 수 있었다.

[Day18] 운동(1956)_김상현.py

---

baekjoon/16172/16172_김상현.py

- **정규 표현식(`Regular Expression`)** 을 활용하여 문제를 해결하였다.
- 파이썬에서는 정규 표현식을 지원하는 **`re`** 모듈을 사용하면 문자을 원하는대로 수정할 수 있다.
```python
if K in ''.join(findall("[a-zA-Z]", S)):
return 1
```
- **`findall()`** 함수는 정규식(`[a-zA-Z]`)과 매치되는 모든 문자열(substring)을 리스트로 돌려준다.
- **`''.join()`** 함수는 매개변수로 들어온 리스트에 있는 요소 하나하나를 합쳐서 하나의 문자열로 바꾸어 반환한다.

[Day19] 나는 친구가 적다(16172)_김상현

---

baekjoon/7569/7569_김상현.py

- **그래스 파이어(`Grass Fire`)** 알고리즘을 이용하여 문제를 해결하였다.
- 수업시간에 배운게 생각나서 사용해보았다.

[Day20] 토마토(7569)_김상현

---

baekjoon/14499/14499_김상현.py

📌 풀이는 요기 [블로그](https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-14499-%EC%A3%BC%EC%82%AC%EC%9C%84-%EA%B5%B4%EB%A6%AC%EA%B8%B0-Python)
- 특별한 알고리즘을 요구하는 문제가 아닌 순수하게 문제의 의도를 파악하고 해결하는 문제입니다.

[Day21] 주사위 굴리기(14499)_김상현

---

baekjoon/1912/1912_김상현.py

```python
for i in range(1,N):
nums[i] = max(nums[i], nums[i] + nums[i-1])
```
- 이전의 값들을 누적으로 더한다.
- 만약 이전까지의 누적합(`nums[i-1]`)에서 현재 값(`nums[i]`)의 합이 현재 값(`nums[i]`) 보다 작다면 이전까지의 누적합은 무시하고 현재 값으로 값을 갱신한다.

[Day22] 연속합(1912)_김상현

---

baekjoon/7453/7453_김상현.py

- **투포인터(`Two Pointer`)** 알고리즘을 적용하여 문제를 해결하였다.
- 너무 **많은 경우의 수가 발생**할 때 이진 탐색(`Binary Search`) 혹은 투 포인터(`Two Pointer`) 알고리즘을 고려해야 한다는 동료의 코멘트가 도움이 되었다.
- 그러나, 아무리 다양한 방법으로 코드를 재 수정하여도 시간초과 문제는 해결할 수 없었다.
- 수 많은 시간초과를 겪고 난 후 다른 훌륭한 개발자 분들의 코드를 참고하여 문제를 해결할 수 있었다.
- 풀이는 틀렸지만 접근 방식은 완전히 엇나가지 않았다는 점이 다행인 것 같다.

[Day23] 합이 0인 네 정수(7453)_김상현

---

baekjoon/2630/2630_김상현.py

- **재귀를 활용한 분할 알고리즘**을 적용하여 문제를 해결하였다.
- 현재 종이를 기준으로 단일색 종이를 만들 수 없다면 현재 종이를 4등분하여 다시 단일색 종이를 만들 수 있는지 재귀적으로 분할하여 결과값을 찾을 수 있었다.
- 분할 알고리즘을 재귀적으로 사용할 때 **재귀가 종료되는 시점**을 찾는 것이 매번 어려웠었는데, 비슷한 유형의 문제를 몇번 접하다보니 어떤 타이밍에 재귀를 종료해야 하는지 감을 잡은 것 같다.

[Day24] 색종이 만들기(2630)_김상현

---

baekjoon/2250/2250_김상현.py

📌 [블로그](https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-2250-%ED%8A%B8%EB%A6%AC%EC%9D%98-%EB%86%92%EC%9D%B4%EC%99%80-%EB%84%88%EB%B9%84-Python)
- 풀이 방법을 알고나서 보면 너무나도 명확하게 보이지만, 모르고 보면은 도저히 방법을 생각해낼 수 없었다.
- **이진 트리**에서 **순서**에 대한 정보를 묻는다면 고려해야할 방법은 **전위 순회(`preorder`)**, **중위 순회(`inorder`)**, **후위 순회(`postorder`)** 이다.
- 이번 문제에 적용한 방법은 **중위 순회(`inorder`)** 이다.
- **중위 순회(`inorder`)**란 왼쪽 하위 트리를 방문 후 뿌리(root)를 방문하고 마지막으로 오른쪽 트리를 방문하는 순회 방법이다.

[Day25] 트리의 높이와 너비(2250)_김상현

---

baekjoon/16401/16401_김상현.py

이진 탐색을 이용하여 조카에게 줄 수 있는 막대 과자의 최대 길이를 찾는다.
https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-16401-%EA%B3%BC%EC%9E%90-%EB%82%98%EB%88%A0%EC%A3%BC%EA%B8%B0-Python

[Day13] 과자 나눠주기(16401)_김상현

---

baekjoon/2623/2623_김우헌.py

1. 주어진 각 pd의 순서를 deque와 set의 형태로 하나씩 보유합니다.
2. 아직 순서에 들어가지 않은 원소를 하나 고릅니다.
3. 그 원소가 모든 pd순서에 대해서 들어가있으며 첫순서이거나 들어가있지 않다는 조건을 만족하는지 확인합니다.
4. 조건을 만족한다면 해당 원소를 순서에 넣습니다. 2번부터 순서를 반복합니다.
5. 2번에서 모든 원소를 방문했으나 원소를 순서에 넣을 수 없다면 0을 출력하고 종료합니다.
5-1. 그렇지 않고 순서를 모두 결정할 수 있다면 결정한 순서의 원소를 하나씩 출력합니다.
해결 키워드에 위상정렬 기법이 있어 학습을 해봐야겠습니다!

[Day7] 음악프로그램(2623)_김우헌

---

baekjoon/3190/3190_김우헌.py

뱀을 deque로 구현했습니다.
1. 뱀의 현재 머리 방향 한 칸 앞에 뱀의 몸통 혹은 벽이 있는지 검사합니다. (있다면 종료 후 초 출력)
2. 뱀의 현재 머리 방향으로 한 칸 앞으로 간 좌표를 deque의 앞에 삽입합니다.
3. 이동한 좌표에 사과가 있는지 검사합니다. (사과가 없다면 deque.pop() 연산 수행 -> 몸통 이동)
4. 현재 초에 머리를 이동할지 확인합니다.
5. 시간을 증가시키고 1부터 반복합니다.

[Day11] 뱀(3190)_김우헌

---

baekjoon/11399/11399_김상현.py

📌 [[알고리즘] BOJ 11399 ATM #Python](https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-11399-ATM-Python)
- 문제에서 **주어진 정보**를 잘 살펴보면 풀이 방법을 알 수 있다.
```
예를 들어, 총 5명이 있고, P1 = 3, P2 = 1, P3 = 4, P4 = 3, P5 = 2 인 경우를 생각해보자.
.
.
.
줄을 [2, 5, 1, 4, 3] 순서로 줄을 서면,
2번 사람은 1분만에,
5번 사람은 1+2 = 3분,
1번 사람은 1+2+3 = 6분,
4번 사람은 1+2+3+3 = 9분,
3번 사람은 1+2+3+3+4 = 13분이 걸리게 된다.
```
- 위의 지문은 문제의 2번째 문단에서 발췌한 지문이다.
- 이 지문을 통해서 알 수 있는 점은 2가지이다.
- 첫 번째는 각 사람이 돈을 인출하는데 필요한 시간의 합의 최소값을 구하려면 돈을 인출하는 순서는 인출하는 시간(`P`)이 가장 적은 순서(`내림차순`)대로 진행해야 한다는 점이다.
- 두 번재는 문제에서 얻고자 하는 각 사람이 돈을 인출하는데 필요한 시간의 합의 값은 인출하는 시간(`P`)이 가장 적은 순서대로 `N, N-1, N-2, ... , 2, 1` 숫자만큼의 시간이 소요된다는 점이다.
- 위의 두 방법을 적용하면 문제를 해결할 수 있다.

[Day26] ATM(11399)_김상현

---

baekjoon/16398/16398_김상현.py

📌 블로그 : [[알고리즘] BOJ 16398 행성 연결 #Python](https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-16398-%ED%96%89%EC%84%B1-%EC%97%B0%EA%B2%B0-Python)
- 문제를 보자마자 싸이클이 발생하지 않는 최단 거리의 경로부터 추가하여 모든 정점을 최소 비용으로 연결하는  `크루스칼(Kruskal) 알고리즘`이 생각이 났다.
- `union()` 과 `find()` 코드만 복사해와서 코드를 작성했는데 한번에 테스트를 통과할 수 있었다.

[Day27] 행성 연결(16398)_김상현

---

baekjoon/1719/1719_김상현.py

📌 블로그 : [[알고리즘] BOJ 1719 택배 #Python](https://velog.io/@isayaksh/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-BOJ-1719-%ED%83%9D%EB%B0%B0-Python)
- 처음 풀이 방법은 **힙(`heap`) 자료구조**를 활용한 **다잌스트라(`Dijkstra`)** 알고리즘을 적용하여 한 집하장에서 다른 집하장으로 최단경로로 화물을 이동시키기 위해 가장 먼저 거쳐야 하는 집하장 정보를 구할 수 있었다.
- 내가 푼 방법 이외에 더 좋은 문제 풀이 방법이 있는지 확인하기 위해서 구글링을 했는데 **플로이드워셜(`Floyd-Warshall`)** 알고리즘을 확인할 수 있었다.
- 다잌스트라 알고리즘을 이용한 코드와 플로이드워셜 알고리즘을 이용한 코드의 수행 시간 차이를 확인하고자 플로이드워셜 알고리즘을 적용한 코드를 작성하여 테스트를 수행하였고 아래와 같은 결과를 얻을 수 있었다.
- 플로이드워셜 알고리즘을 이용한 코드가 다잌스트라 알고리즘을 이용한 코드의 3배 빠른 효율을 보여주었다.
- 다잌스트라 알고리즘을 적용하여 문제는 해결할 수 있었지만 제일 최적의 알고리즘을 생각해내지 못한 것이 무척 아쉽다.

[Day28] 택배(1719)_김상현

---

baekjoon/7795/7795_김상현.py

- 두 종류의 생명체 A, B를 크기 순으로 정렬한 후 **이진 탐색(`Binary Search`)** 을 적용하면 A의 크기가 B보다 큰 쌍이 몇 개나 있는지 구할 수 있다.
- 파이썬 라이브러리 중에 이진 탐색을 위한 `bisect` 가 존재한다.
→ 📒 [bisect — 배열 이진 분할 알고리즘](https://docs.python.org/ko/3/library/bisect.html)
- `bisect_left` 함수는 주어진 리스트에서 자신보다 크거나 같은 값의 왼쪽 index 값을 반환한다.
- `bisect_left` 함수를 활용하여 A의 크기가 B보다 큰 쌍이 몇 개나 있는지 구할 수 있다.

[Day29] 먹을 것인가 먹힐 것인가(7795)_김상현

---

baekjoon/2206/2206_김상현.py

- 그래프 탐색 문제에서 벽을 부수거나, 벽을 뛰어 넘거나, 혹은 횟수 제한이 있는 특별한 이동 방식이 존재하는 경우 기존 2차원 배열을 사용하는 `visited` 배열을 **3차원**으로 구성하여 특수한 이동 방식의 사용 여부를 구별할 수 있다.

[Day30] 벽 부수고 이동하기(2206)_김상현

---

baekjoon/16401/16401_김우헌.py
baekjoon/9251/9251_김우헌.py

이진탐색으로 나눌 과자의 길이를 정합니다.
과자들중 가장 큰 길이의 과자를 이진탐색의 끝점으로, 시작점은 0으로 해서 이진탐색을 진행합니다.
특정 mid 길이로 과자를 나눴을 때 요구사항과 맞아떨어지더라고 더 크게 자를 수 있는 경우의 수가 남아있으므로 현재 과자의 길이를 result 변수에 저장한 뒤 이진탐색을 계속 진행합니다.

[Day13] 과자 나눠주기(16401)_김우헌

---

baekjoon/14267/14267_김상현.py
baekjoon/16987/16987_김상현.py
baekjoon/1744/1744_김상현.py

- 음수의 개수가 홀수인 경우 2개씩 묶고 남은 1개의 음수와 `0`을 묶어서 음수가 아닌 0의 값을 만드는 것이 `0`이 할 수 있는 최선의 경우이다.
- 거의 모든 경우에서 두 양수를 곱하는 것이 최대의 수를 만드는 경우가 맞지만, 두 양수 중 `1`이 존재한다면 두 양수를 곱하는 것 보다 더하는 것이 최대의 수를 만들 수 있는 경우이다.

[Day36] 수 묶기(1744)_김상현

---

baekjoon/2660/2660_김우헌.py

플루이드-와샬 기법을 통해 간단하게 풀 수 있는 문제입니다.
주어진 친구사이를 그래프 간선으로 표현하고, 각 노드간의 길이를 1이라고 가정한뒤
플루이드-와샬 기법으로 모든 친구 사이의 관계 거리를 구해서 문제를 해결합니다.
한 노드에서 다른 모든 노드와의 거리 중 최대값이 해당 사람의 점수이며
최소점수, 최소점수를 가진 사람의 수, 최소점수를 가진 사람 번호를 차례대로 출력합니다.

[Day15] 회장뽑기(2660)_김우헌
